### ISSUE TITLE
How to specify -I (include paths) to moc compiler with CxxQtBuilder.qobject_header()?

### ISSUE THREAD

**Issue by haata** [KDAB/cxx-qt#679]
For this snippet to pass the moc compiler I need to pass in a `-IOpenRGB` for it to work correctly.

```cpp
  class OpenRGBPluginInterfaceWrapper : public QObject, public OpenRGBPluginInterface
  {
      Q_OBJECT
      Q_PLUGIN_METADATA(IID OpenRGBPluginInterface_IID)
      Q_INTERFACES(OpenRGBPluginInterface)
  public:
      OpenRGBPluginInterfaceWrapper(QObject* parent);
      ~OpenRGBPluginInterfaceWrapper();
```

Otherwise I'll get errors like:
```bash
: moc OpenRGBSamplePlugin.h         
OpenRGBSamplePlugin.h:23: Parse error at "IID"
```
and (commenting out Q_PLUGIN_METADATA).
```bash
OpenRGBSamplePlugin.h:24: Error: Undefined interface
```

This works:
```bash
moc -IOpenRGB OpenRGBSamplePlugin.h
```

I've looked through the code for cxx-qt-build and it's not clear if there is a way to do this.

**Comment by ahayzen-kdab** [comment]
Thank for you taking this time to point this out.

We don't support custom arguments for `moc` yet, this would likely need to go into `qt-built-utils` and then `cxx-qt-build`.

Assume these have to be passed to moc and can't be picked up from the C++ includes :-/ 

We should figure out what other custom arguments might need to be given to moc as well.

For now the workaround would be to do this in CMake or run moc manually if using a cargo build.

**Comment by haata** [comment]
I'm going to try and see if I can work around it with C++ includes.

I'm having some trouble getting my code to compile with 0.6 so it may be my best option for now.
I'll also post a POC PR to add -I to main.

**Comment by ahayzen-kdab** [comment]
As part of the build system refactor for #1065 etc we should consider this, cc @LeonMatthesKDAB

**Comment by LeonMatthesKDAB** [comment]
This should be fixed now, you can specify Moc Arguments (including `-I`) via the QObjectHeaderOpts.
